### ISSUE TITLE
Trouble with node exif in function

### ISSUE THREAD

**Issue by andrewboni** [gomfunkel/node-exif#28]
I'm getting `node-exif` to work, but not in the way I want.

I have the following code:

```javascript
function getExifInfo(args){
    var file = args[0], info = "testing";
    var ExifImage = require('exif').ExifImage;
    try {
        new ExifImage({ image: file }, function (error, exifData) {
            if(error) {
                console.log("something went wrong");
            } else {
                info = '<p>' + exifData.image.Model + ' | ' + exifData.exif.FocalLength +'mm | ' + exifData.exif.ExposureTime * 1000 + 'ms exposure | ƒ/' +
                    exifData.exif.FNumber + ' | ' + 'ISO' + exifData.exif.ISO + '</p>';
                console.log("info 1 is " + info);
            }
        });
    } catch(error) {
        console.log("Error: " + error);
    } finally {
        console.log("info 2 is " + info);
        return info;
    }
}
```

With the following console output:
```bash
info 2 is testing
info 1 is <p>NIKON D7000 | 35mm | 5ms exposure | ƒ/7.1 | ISO200</p>
```
Maybe I'm missing something, but I was expecting the function `getExifInfo()` to return the `exif` info, not the string `"testing"`. Any ideas? Thanks!

**Comment by lacombar** [comment]
You are expecting a synchronous behavior of this asynchronous snippet. The Exif information are returned in the anonymous function passed to the constructor upon success, not the parent calling it. This callback has its own context. When the callback exits, the content of `info' is lost.
