### ISSUE TITLE
`new ExifImage` callback can be called twice

### ISSUE THREAD

**Issue by markwainwright** [gomfunkel/node-exif#29]
I have a very simple method that looks like this:

```
console.log('Method called');
new ExifImage({image: image}, function(error, exif) {
  console.log(error);
});
```

With a certain image, the callback is called twice, each with a different error.

Here's the console after calling the method:

```
Method called
[Error: The Exif data is not valid.] undefined
[Error: No Exif segment found in the given image.] undefined
```

I'm using v0.4.0.

Thanks!

**Comment by qqilihq** [comment]
Having the same issue here. Is there any reason why this fix has not yet been merged?
