### ISSUE TITLE
ModifyDate, DateTimeOriginal, CreateDate formats with : instead of -

### ISSUE THREAD

**Issue by elgubenis** [gomfunkel/node-exif#37]
hi,

my exif data is containing these key/values

ModifyDate: '2015:04:14 09:12:53'
DateTimeOriginal: '2015:04:14 09:12:53'
CreateDate: '2015:04:14 09:12:53'

where i think that the date-values should be seperated by - instead of : or am i missing something?

**Comment by jeffklassen** [comment]
Disclaimer: I'm not the package maintainer.

Would you please give some more reasoning in your bug request? It seems that if you want to change the delimiter, you could simply:

    var dateTimeString = '2015:04:14 09:12:53';
    var timeString = dateTimeString.substring(dateTimeString.indexOf(' '));
    var dateString = dateTimeString.substring(0,dateTimeString.indexOf(' '));
    dateString = dateString.replace(/\:/g, '-');

    dateTimeString = dateString+" " + timeString;

**Comment by elgubenis** [comment]
sorry, i did not know that the default format for exif timestamp was with : as date-fragment-delimiter.
