### ISSUE TITLE
Only able to process 2048 files

### ISSUE THREAD

**Issue by tlauritzen** [gomfunkel/node-exif#54]
It looks like node-exif is only able to open 2048 files at a time. Have you considered using [graceful-fs](https://github.com/isaacs/node-graceful-fs), instead of the standard node fs? It might slow things down a little bit, but I would be willing to pay that price. It could also be an option to use graceful-fs.

/Torben

**Comment by oeuillot** [comment]
Perhaps, there is a file identifier leak somewhere ?
How do you call node-exif ?

Regards,

2016-03-10 14:52 GMT+01:00 Torben Lauritzen <notifications@github.com>:

**Comment by tlauritzen** [comment]
I was calling it with a filename (3000 files):

`new ExifImage(filename, function(error, exifData) {}`

But I have found a workaround - ExifImage also works with a buffer, so now I use graceful-fs to open my files, and call `new ExifImage(buffer, function(error, exifData) {}`. Works like a charm! :-)

Thank you very much for your work - it is really helpful!

/Torben

**Comment by oeuillot** [comment]
Perhaps a resource leak in some node version of
fs.readFile(image, function (error, data) {})
