### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by mdcleber** [gomfunkel/node-exif#67]
There is a problem in the date format, every date properties like "CreateDate" or "ModifyDate" is using the caracter ":" to separete year, month and day and normaly we use de caracter "/" to separete the data.
This causing me some problems when i try to convert a string to a Date object being  necessary to use a substrig together with replace

Sorry for the bad english is not my native language.

**Comment by MichaelBorde** [comment]
Sorry to reply to this old issue but may be you could use moment to parse and format the date to your liking.

An example:

`const moment = require('moment');

const m = moment('2000:08:04 18:22:57', 'YYYY:MM:DD HH:mm:ss');
const dateString = m.format('YYYY/MM/DD HH:mm:ss');
console.log(dateString);
// 2000/08/04 18:22:57
`

**Comment by oeuillot** [comment]
For node-exif the data are strings, numbers or buffers. It is your responsibility to transform them to date object.
